### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ws-garcia** [sdkn104/VBA-CSV#3]
Currently, I am improving the `CSVinterface` class to make it RFC4180 standard fully compliant. As you know, your well developed project is used by me as a reference.

I test your code using the following CSV text and the returned value by your `ParseCSVToArray` function is `null`:
```
"Field with 
multiple lines" , "Another field 
with some 
line breaks inside" , "Include some  comma, for test" , Normal field here
1, 2, 3 ,4 
"Field 1", "Field 2" , Field 3 , "Field 4"
```
The above CSV complies the RFC4180 standard.

**Comment by sdkn104** [comment]
Thank you for reporting.
I tired your CSV text but ParseCSVToArray does not return null.
I have tried both case of return code CR and CRLF.
My test code is:
```
    Dim csv As Variant
    Dim csvText As String
    csvText = readFile("C:\Users\xxxx\desktop\test.txt")  'readFile is defined in CSVUtils_Example.
    csv = ParseCSVToArray(csvText)
    If IsNull(csv) Then
        Debug.Print Err.Number & " (" & Err.Source & ") " & Err.Description
    End If
```
"test.txt" contains your CSV text.
What is your situation ?

**Comment by ws-garcia** [comment]
The CSV text is on a ANSI codified file, when I tried to parse it, using your well documented code, I got an `null` value returned.

**Comment by ws-garcia** [comment]
First, I defined `SDKNstrArray As Variant` ; and then I make a call `SDKNstrArray = ParseCSVToArray(tmpCSV)`, were the argument was defined as `tmpCSV As String`. The inspection window show me the `null` value returned after call the function.

**Comment by ws-garcia** [comment]
After a look to your response:
`SDKNstrArray = ParseCSVToArray(tmpCSV)
If IsNull(SDKNstrArray) Then
        Debug.Print Err.Number & " (" & Err.Source & ") " & Err.description
End If`
The above prints the text `10001 (ParseCSVToCollection) Syntax Error in CSV: numbers of fields are different among records` in the immediate window.

**Comment by ws-garcia** [comment]
After a look to your response:

```
SDKNstrArray = ParseCSVToArray(tmpCSV) 
If IsNull(SDKNstrArray) Then 
    Debug.Print Err.Number & " (" & Err.Source & ") " & Err.description 
End If
```
The above prints the text `10001 (ParseCSVToCollection) Syntax Error in CSV: numbers of fields are different among records` in the immediate window.

**Comment by sdkn104** [comment]
I tried the following code.
```
    Dim csv As Variant
    Dim csvText As String
    csvText = """Field with" & vbCr & _
                "multiple lines"" , ""Another field" & vbCr & _
                "With some" & vbCr & _
                "line breaks inside"" , ""Include some  comma, for test"" , Normal field here" & vbCr & _
                "1, 2, 3 ,4" & vbCr & _
                """Field 1"", ""Field 2"" , Field 3 , ""Field 4"""
    Debug.Print csvText
    csv = ParseCSVToArray(csvText)
    If IsNull(csv) Then
        Debug.Print Err.Number & " (" & Err.Source & ") " & Err.Description
    End If
    Debug.Print UBound(csv, 1)
    Debug.Print UBound(csv, 2)
```
The result in immediate window is
```
"Field with
multiple lines" , "Another field
With some
line breaks inside" , "Include some  comma, for test" , Normal field here
1, 2, 3 ,4
"Field 1", "Field 2" , Field 3 , "Field 4"
 3 
 4 
```
Please check it.

**Comment by ws-garcia** [comment]
The file has some space chars not included in your above test:
"Field with` `
multiple lines" ,"Another field` `
with some` `
line breaks inside" , "Include some  comma, for test" , Normal field here` `
1, 2, 3 ,4` `
"Field 1", "Field 2" , Field 3 , "Field 4"

But, I think the main problem here is that the file actually use `vbCrLf` instead `vbCr` char

However, I will check if there are additional `vbCrLf` chars in the CSV file that potential may cause the cited error in your code.
![Captura de pantalla (86)](https://user-images.githubusercontent.com/70865364/94995176-976b5c80-056a-11eb-8144-a0f015cf0651.png)

**Comment by ws-garcia** [comment]
Definitely, the are an extra `vbCrLf` char into the CSV file. This file issue break the logic and generate an error. After remove it, your code successful import the data. Thanks for your replies!
